export const FETCH_PLACE_AUTOCOMPLETE           = 'FETCH_PLACE_AUTOCOMPLETE';
export const CLEAR_PLACE_AUTOCOMPLETE           = 'CLEAR_PLACE_AUTOCOMPLETE';
export const TOGGLE_DROPDOWN_PLACE_AUTOCOMPLETE = 'TOGGLE_DROPDOWN_PLACE_AUTOCOMPLETE';
export const ON_SELECT_PLACE_AUTOCOMPLETE       = 'ON_SELECT_PLACE_AUTOCOMPLETE';
